[package]
name = "rust-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
once_cell = { version = "1" }
bytes = { version = "1" }
raptorq = { version = "2" }
